---
title: "Cleaning Dada2 Output"
author: "Michael Sieler"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
---

## Setup environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)  # Sets default knit settings for document


```

## Import 

### Load Uncleaned PS Object
```{r load-uncleaned-ps-obj}
# File contains info on important variables, analyses and output objects

ps.raw <- readRDS("~/Dropbox/Mac (2)/Documents/Sharpton_Lab/Projects_Repository/Rules_of_Life/RoL_HeaterTrial2021/Data/Output/dada2_1.26.0_2022-11-15_output/phyloseq.rds")

# View(sample.data.frame(ps.raw))
```


## Process PS object

```{r}

rarefaction.minimum <- 5000
min.smpl.size <- min(
  sample_sums(ps.raw)[sample_sums(ps.raw) >= rarefaction.minimum]
)

```


### Rarefy Data

```{r Rarefaction}


ps.rar <- {
    ps.rar <- rarefy_even_depth(
        physeq = ps.raw,
        sample.size = min.smpl.size,
        trimOTUs = TRUE,
        rngseed = 42
          ) %>%
      subset_taxa(
        !is.na(Kingdom) & 
          Kingdom != "Eukaryota" &
          Order != "Chloroplast" &
          Family != "Mitochondria"
    )

    rename.NA.taxa(ps.rar)
} # 23 samples removedbecause they contained fewer reads than min.smpl.size

ps.rar

```

### CLR

```{r}


clr.mat <- gen.clr.matrix(asv.mat = otu.matrix(ps.raw), min_reads = min.smpl.size)
ps.clr <- prune_taxa(colnames(clr.mat), ps.raw)
otu_table(ps.clr) <- otu_table(clr.mat, taxa_are_rows = F)

ps.clr <- {
    ps.clr %>%
      subset_taxa(
        !is.na(Kingdom) & 
          Kingdom != "Eukaryota" &
          Order != "Chloroplast" &
          Family != "Mitochondria"
    )

    rename.NA.taxa(ps.clr)
} 

ps.clr

```




### Visualization

Overview of relative abundance of taxa


```{r}

plot_relAbund_All_Genus <-
  ps.rar %>% 
    tax_agg("Genus") %>% 
    ps_seriate(dist = "bray", method = "OLO_ward") %>% # these are the defaults
    comp_barplot(tax_level = "Genus", sample_order = "asis", n_taxa = 10) +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


plot_relAbund_Fam <- 
  ps.rar %>%
    comp_barplot(
      tax_level = "Family", n_taxa = 15, other_name = "Other",
      taxon_renamer = function(x) stringr::str_remove(x, " [ae]t rel."),
      palette = distinct_palette(n = 15, add = "grey90"),
      merge_other = FALSE, bar_outline_colour = "darkgrey"
    ) +
    coord_flip() +
    facet_wrap(c("Treatment", "Temperature", "DPE"), nrow = 2, scales = "free") +
    # facet_grid(Temperature ~ Treatment, scales = "free", space = "free") +
    labs(x = NULL, y = NULL) +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

plot_relAbund_Gen <- 
  ps.rar %>%
    comp_barplot(
      tax_level = "Family", n_taxa = 15, other_name = "Other",
      taxon_renamer = function(x) stringr::str_remove(x, " [ae]t rel."),
      palette = distinct_palette(n = 15, add = "grey90"),
      merge_other = FALSE, bar_outline_colour = "darkgrey"
    ) +
    coord_flip() +
    facet_wrap(c("Treatment", "Temperature", "DPE"), nrow = 2, scales = "free") +
    # facet_grid(Temperature ~ Treatment, scales = "free", space = "free") +
    labs(x = NULL, y = NULL) +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())


```


```{r}

plot_relAbund_Fam_Temp28 <- 
  ps.rar %>%
    subset_samples(Temperature == 28) %>%
    comp_barplot(
      tax_level = "Family", n_taxa = 15, other_name = "Other",
      taxon_renamer = function(x) stringr::str_remove(x, " [ae]t rel."),
      palette = distinct_palette(n = 15, add = "grey90"),
      merge_other = FALSE, bar_outline_colour = "darkgrey"
    ) +
    coord_flip() +
    facet_wrap(c("Treatment", "Temperature", "DPE"), nrow = 2, scales = "free") +
    # facet_grid(Temperature ~ Treatment, scales = "free", space = "free") +
    labs(x = NULL, y = NULL) +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

plot_relAbund_Fam_Temp32 <- 
  ps.rar %>%
    subset_samples(Temperature == 32) %>%
    comp_barplot(
      tax_level = "Family", n_taxa = 15, other_name = "Other",
      taxon_renamer = function(x) stringr::str_remove(x, " [ae]t rel."),
      palette = distinct_palette(n = 15, add = "grey90"),
      merge_other = FALSE, bar_outline_colour = "darkgrey"
    ) +
    coord_flip() +
    facet_wrap(c("Treatment", "Temperature", "DPE"), nrow = 2, scales = "free") +
    # facet_grid(Temperature ~ Treatment, scales = "free", space = "free") +
    labs(x = NULL, y = NULL) +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

plot_relAbund_Fam_Temp35 <- 
  ps.rar %>%
    subset_samples(Temperature == 35) %>%
    comp_barplot(
      tax_level = "Family", n_taxa = 15, other_name = "Other",
      taxon_renamer = function(x) stringr::str_remove(x, " [ae]t rel."),
      palette = distinct_palette(n = 15, add = "grey90"),
      merge_other = FALSE, bar_outline_colour = "darkgrey"
    ) +
    coord_flip() +
    facet_wrap(c("Treatment", "Temperature", "DPE"), nrow = 2, scales = "free") +
    # facet_grid(Temperature ~ Treatment, scales = "free", space = "free") +
    labs(x = NULL, y = NULL) +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

plot_relAbund_Fam_Temp28
plot_relAbund_Fam_Temp32
plot_relAbund_Fam_Temp35

```



## Export

### Save Phyloseq Object

```{r save-ps-obj}
# # saveRDS(ps, file = file.path(paste0(objects.path, "/phyloseq_cleaned_", Sys.Date(),".rds")))
# 
# # Save PS obj, sample data table cleaned
# saveRDS(ps0, file = file.path(paste0(objects.path, "/phyloseq_sampData_cleaned_Outliers_", Sys.Date(),".rds")))
# clean.ps.obj <- paste0(objects.path, "/phyloseq_sampData_cleaned_Outliers_", Sys.Date(),".rds")
# 
# # Save PS obj, no outliers
# saveRDS(ps1, file = file.path(paste0(objects.path, "/phyloseq_sampData_cleaned_noOutliers_", Sys.Date(),".rds")))
# 
# # # Save PS obj, samp data cleaned, no outliers, rarefied
# saveRDS(ps1.rar, file = file.path(paste0(output.path, "/phyloseq_cleaned_rarefied_", Sys.Date(),".rds")))

# Save PS obj, rarefied
saveRDS(ps.rar, file = file.path(path.data, "R_objects", paste0("phyloseq_rarefied_", Sys.Date(),".rds")))

# Save PS obj, clr
saveRDS(ps.clr, file = file.path(path.data, "R_objects", paste0("phyloseq_clr_", Sys.Date(),".rds")))


# Save Environment
save_env(file.path(path.data, "R_objects"),
         extra_info = "cleaning_data2_output_")
```
